meta_product_name: "Pawsitter"
meta_title: "Pawsitter - Your pet's bestfriend when you're away"
meta_description: "Find a reliable petsitter near you"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
